apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phpinfo-helm
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: gitops-targets
      requeueAfterSeconds: 60
  template:
    metadata:
      name: phpinfo-helm-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: phpinfo-helm
      source:
        repoURL: https://github.com/sebastian-colomar/phpinfo.git
        targetRevision: HEAD
        path: main/helm/apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
