apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: register-spokes-to-gitops
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
  argoNamespace: openshift-gitops
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: gitops-targets
