apiVersion: v1
baseDomain: sebastian-colomar.com
compute:
- architecture: arm64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: t4g.large
  replicas: 3
controlPlane:
  architecture: arm64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: t4g.xlarge
  replicas: 3
metadata:
  name: provider-aws-helm-3
networking:
  clusterNetwork:
  - cidr: 10.133.0.0/16
    hostPrefix: 20
  machineNetwork:
  - cidr: 10.3.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.33.0.0/16
platform:
  aws:
    region: ap-south-1
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwri0pp7r3vzhRxY+8FHI4h7UKcRQEV/uSUckAYwvEeK4Io6okdb+Vd/Ons/wX1CChEvKWlShklCiR03rEFgJoRMAB8bv/z+VC/VC+iltcJq1tY2/YEOZKYOCEisqYEIJ6F2nls66ePZHs84RTbmvpyCH81o+5PaZx9WoFH+PkGANuwferqTclhIY8TTOuwo8cQICo62wMtHKNphZQ2GA8IGHy5rwp9V/12d8cVqtIrxG2XQYgXrrhoTb7SgzC/IIjRxLokzzOHaVIA+kuS9aWSHTpn3+1QWbthJL7HY4xqfaeVmUA75MFLxJ5Wa/ApD+T1qhPQJ2EFUJkB84/H1dUP274L90l9xjqsRZqx0lrK+uPcTwQ98d09jzvEC07ueL3FAI4oyLOdQwrYkkOvQy423pOQWTJ0FA5/7Xcef8CxCTF+eFB9hvpDZCWehzNaycqA3+4fy6O/qW156rJxQYsq0V+nzg2XZIh6gD8fqWILkP/Hcndm06eGUcooDHwiFc=
