apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phpinfo-helm-provider-aws-helm-evens
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: provider-aws-helm-evens
      requeueAfterSeconds: 30
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: 'phpinfo-helm-{{name}}'
    spec:
      destination:
        namespace: phpinfo-helm
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
        path: main/apps/helm
        repoURL: https://github.com/sebastian-colomar/phpinfo
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
