apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-application-manifestworkreplicasets
  namespace: openshift-gitops
rules:
- apiGroups: ["work.open-cluster-management.io"]
  resources: ["manifestworkreplicasets"]
  verbs: ["create"]
