apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route-patcher
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: route-patcher
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: route-patcher
  apiGroup: rbac.authorization.k8s.io
