apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-patcher
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["config.openshift.io"]
  resources: ["dnses"]
  verbs: ["get"]
