apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "50"
    haproxy.router.openshift.io/timeout: 30m
  name: mirror-quay-internal
  namespace: openshift-operators
spec:
  host: mirror-quay-openshift-operators.apps-int.BASEDOMAIN
  to:
    kind: Service
    name: mirror-quay-app
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
