apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "50"
    haproxy.router.openshift.io/timeout: 30m
  name: {{ .Values.registry.name }}-quay-internal
  namespace: {{ .Values.namespace }}
spec:
  #host: {{ .Values.registry.name }}-quay-{{ .Values.namespace }}.apps-int.basedomain
  to:
    kind: Service
    name: {{ .Values.registry.name }}-quay-app
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
