apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "30"
  labels:
    operators.coreos.com/quay-operator.openshift-operators: ''
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
