apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: BASEDOMAIN
    objRef:
      apiVersion: config.openshift.io/v1
      kind: DNS
      name: cluster
    fieldRef:
      fieldPath: spec.baseDomain
resources:
  - route.yaml
