apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  plugins:
  - acm
  - gitops-plugin
  - mce
  - monitoring-plugin  
  - networking-console-plugin
  - odf-console
