apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "20"
  name: {{ .Values.namespace }}-operatorgroup
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.namespace }}
  upgradeStrategy: Default
