apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-apps-repo
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: hub-local-cluster
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: odf-label-worker-nodes
