apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: provider-aws-ocp-1
  namespace: provider-aws-ocp-1
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterName: provider-aws-ocp-1
  clusterNamespace: provider-aws-ocp-1
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
