apiVersion: v1
kind: Secret
metadata:
  name: provider-aws-ocp-1-install-config
  namespace: provider-aws-ocp-1
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: sebastian-colomar.com
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform:
        aws:
          type: t3a.xlarge
      replicas: 3
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform:
        aws:
          type: t3a.large
      replicas: 3
    metadata:
      name: provider-aws-ocp-1
    networking:
      clusterNetwork:
      - cidr: 10.131.0.0/16
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.1.0.0/16
      networkType: OVNKubernetes
      serviceNetwork:
      - 172.31.0.0/16
    platform:
      aws:
        region: ap-south-1
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtIVnMlmk2yvD9XqAtygyv4GcScKNIVoYeD2XZ+rVILFnW+K2A4Do+DLE4pA6Je80H7GP0N6d2sVEWyjp+qk0t9ezhoytT0mZ/pMJYsQI1fxiVhL7+3+leIcVxhnaXUFozyE0E9kbVmnPV4kAjiVARvkACs/+RsrA1BUrOrQy2QhFPg9C/HP7pOu5xTA0mVubeB/8FWlSqoCuegb2mYalEBhTlTpUAfgTM1ou0FmJIdMorJgkcsJGs4t9hMYaWMSdtMKATd+Aput7umj4TxRXJ7NRF6SbP6L1UatDP8812BdsRhywPD9wa0Mc3hgEwiD+oE7w+HrnIv5Kx3RFpEtPf
type: Opaque
