aws:
  region: ap-south-1
cluster:
  baseDomain: sebastian-colomar.com
  #baseDomain: sebastian-colomar.es
  cloud1: Amazon
  cloud2: AWS
  clusterset: provider-aws-helm
  image: img4.17.47-multi-appsub
  #image: img4.20.10-multi-appsub
  name: provider-aws-helm-3
  platform: aws
  vendor: OpenShift
gitops:
  name: openshift-gitops
  namespace: openshift-gitops
machinepools:
  - 
    name: worker
    #replicas: 2
    replicas: 3
    rootVolume:
      iops: 2000
      size: 100
      type: io1
    type: t3a.large
    #type: t4g.large
