apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-applicationset-placementdecisions
  namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-applicationset-placementdecisions
