apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: install-gitops-on-minions
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster-role: minion
  template:
    metadata:
      name: gitops-operator-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/sebastian-colomar/hive-through-gitops
        targetRevision: HEAD
        path: apps/minions/gitops-install
      destination:
        server: "{{server}}"
        namespace: openshift-operators
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
