apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: provider-aws-helm
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: '1'
      - cluster: '2'
      #- cluster: '3'
      #- cluster: '4'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        applicationset: provider-aws-helm
      name: provider-aws-helm-{{ cluster }}
    spec:
      destination:
        namespace: provider-aws-helm-{{ cluster }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
          - clusters/provider-aws-helm-{{ cluster }}/values.yaml
        path: provider-aws/apps/02-managed-clusters-deploy/helm
        repoURL: https://github.com/sebastian-colomar/hive-through-gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - ServerSideApply=true
