apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-argocd
  namespace: openshift-gitops
rules:
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["placementbindings"]
  verbs: ["patch"]
